image: registry.labs.nic.cz/turris/foris-ci

stages:
  - test

test:
  stage: test

  script:

    - git clone https://gitlab.labs.nic.cz/turris/foris-schema.git
    - cd foris-schema
    - (git checkout refs/remotes/origin/${CI_COMMIT_REF_NAME} || true)
    - pip install .
    - cd ..

    - pip install .

    - git clone https://gitlab.labs.nic.cz/turris/foris-controller-testtools.git
    - cd foris-controller-testtools
    - (git checkout refs/remotes/origin/${CI_COMMIT_REF_NAME} || true)
    - pip install .
    - cd ..

    - pip install .

    - git clone https://gitlab.labs.nic.cz/turris/foris-client.git
    - cd foris-client
    - (git checkout refs/remotes/origin/${CI_COMMIT_REF_NAME} || true)
    - pip install .
    - cd ..

    - export LD_LIBRARY_PATH=:/usr/local/lib
    - python setup.py test
    - python setup.py test --addopts="--backend openwrt"

    - cd doc/examples/sample_module/
    - pip install .
    - python setup.py test
    - python setup.py test --addopts="--backend openwrt"
