image: registry.labs.nic.cz/turris/foris-ci

stages:
  - test

test:
  stage: test

  script:
    - git clone https://gitlab.labs.nic.cz/turris/foris-schema.git
    - cd foris-schema
    - python setup.py install
    - cd ..
    - python setup.py install
    - export LD_LIBRARY_PATH=:/usr/local/lib
    - python setup.py test
