before_script:
  - pip install virtualenv
  - virtualenv -p "$(which python)" /tmp/test

stages:
  - test

.run_script: &run_script
  script:
    - source /tmp/test/bin/activate

    - pip install .

    # unit tests
    - python setup.py test --addopts="--backend openwrt --message-bus mqtt tests/unit/"

    # blackbox production config
    - python setup.py test --addopts="--backend openwrt --message-bus mqtt tests/blackbox/"

    # production bus + mock backend
    - python setup.py test --addopts="--backend mock --message-bus mqtt tests/blackbox/"

    # production backend + ubus bus
    - python setup.py test --addopts="--backend openwrt --message-bus ubus tests/blackbox/"

    # production backend + unix-socket bus
    - python setup.py test --addopts="--backend openwrt --message-bus unix-socket tests/blackbox/"

    # render cookiecutter template
    - pip install cookiecutter
    - rm -rf /tmp/cookiecutter/
    - cookiecutter --no-input doc/examples -o /tmp/cookiecutter/

    # install sample modole
    - cd /tmp/cookiecutter/sample_example/
    - pip install .

    # test both backends here
    - python setup.py test --addopts="--backend openwrt --backend mock --message-bus mqtt --message-bus ubus"

test_python3:
  image: registry.labs.nic.cz/turris/foris-ci/python3
  stage: test
  <<: *run_script
